### ISSUE TITLE
text subliniat cu rosu

### ISSUE THREAD

**Issue by mess110** [OvidiuCaba/StatisticsRomania#1]
![screenshot_2016-02-22-15-00-01](https://cloud.githubusercontent.com/assets/226170/13218871/0ae5c80c-d975-11e5-8cb7-775eeb866631.png)

Minor:

1. De ce e numele orasului subliniat cu rosu?
2. "Castigul salarial mediu" e subliniat "brut" nu e
3. Default value pt oras nu e subliniat. Devine subliniat daca schimb valoarea. Daca inchid si redeschid aplicatia (killing the process), nu e subliniat.

**Comment by OvidiuCaba** [comment]
Am vazut problema. Am impresia ca e de la autocorrect, nu sunt sigur. Trebuie sa investighez si sa rezolv. Multumesc pentru observatie.

**Comment by OvidiuCaba** [comment]
Rezolvat! Va fi disponibil in urmatoarea versiune a aplicatiei. Cel mai probabil pe maine dimineata.
