### ISSUE TITLE
nu pot sa deselectez un rand din tabel

### ISSUE THREAD

**Issue by mess110** [OvidiuCaba/StatisticsRomania#2]
![screenshot_2016-02-22-15-00-01](https://cloud.githubusercontent.com/assets/226170/13218871/0ae5c80c-d975-11e5-8cb7-775eeb866631.png)

Cand dau "click" pe o coloana din tabel o selectez. Se face albastra. Daca dau din nou "click" pe ea nu se de-selecteaza.

**Comment by OvidiuCaba** [comment]
Asta e comportamentul default al pluginului folosit. Am vazut si eu comportamentul si ma intrebam daca sa-l scot sau nu. Acuma, ca l-ai vazut si tu si imi spui ca te deranjeaza, am sa incerc s-al scot :) Cred ca e util doar pentru tabele cu coloane multe, ca sa nu te pierzi, sa stii pentru ce item/judet citesti informatia. In cazul de fata nu se justifica acel rand selectat.

**Comment by OvidiuCaba** [comment]
Rezolvat. Va fi disponibil in urmatorul update, probabil pe maine dimineata.
