### ISSUE TITLE
valori default pt Clasamente

### ISSUE THREAD

**Issue by mess110** [OvidiuCaba/StatisticsRomania#5]
Pe tabul de clasamente:

Daca aleg doar anul, nu apare nimic. Trebuie sa aleg luna.

O varianta ar fi sa ai default values si/sau sa marchezi campurile obligatorii

**Comment by OvidiuCaba** [comment]
Voi merge pe varianta default values. Apoi, pe masura ce modifici parametrii, se reimprospateaza clasamentul. Multumesc pentru obesrvatie.

**Comment by OvidiuCaba** [comment]
Rezolvat. Va fi disponibil in urmatoarea versiune a aplicatiei, probabil pe maine dimineata.
