### ISSUE TITLE
"no data" warning

### ISSUE THREAD

**Issue by mess110** [OvidiuCaba/StatisticsRomania#6]
Ar fi fain sa vedem ceva text care zice ca nu sunt date cand nu sunt date :)

De exemplu, pe tabul de clasamente pt anul 2014 luna 1 nu apare nimic.

**Comment by OvidiuCaba** [comment]
Rezolvat. Din pacate controlul nu are built-in asa ceva, asa ca ascund gridul daca nu sunt date si afisez un label cum ca nu sunt date. Tot e mai bine decat sa nu se intample nimic, ca asa utilizatorul poate crede ca s-a stricat aplicatia, ca el nu are de unde sa stie daca sunt date or ba.
